"use client";

import { Sparkles, CheckCircle2, ChevronRight, Clock, ShieldAlert, Code2 } from "lucide-react";

export default function FixesPage() {
  const fixes = [
    {
      id: "FIX-104",
      issueId: "42",
      title: "Add proper exception throwing to login endpoint",
      file: "auth.py",
      status: "applied",
      testStatus: "passed",
      confidence: 96,
      completedAt: "2 hours ago"
    },
    {
      id: "FIX-103",
      issueId: "89",
      title: "Add safeguard check for null object in profile user retrieval",
      file: "database.py",
      status: "applied",
      testStatus: "passed",
      confidence: 98,
      completedAt: "1 day ago"
    },
    {
      id: "FIX-102",
      issueId: "145",
      title: "Adjust docker connection timeout flags in setup scripts",
      file: "Dockerfile",
      status: "reviewing",
      testStatus: "running",
      confidence: 85,
      completedAt: "Just now"
    },
    {
      id: "FIX-101",
      issueId: "38",
      title: "Sanitize URL path prefixes for routes loading page configuration",
      file: "routes/user.py",
      status: "rejected",
      testStatus: "failed",
      confidence: 60,
      completedAt: "3 days ago"
    }
  ];

  return (
    <div className="p-6 max-w-6xl mx-auto space-y-6">
      {/* Header */}
      <div>
        <h2 className="text-xl font-bold text-slate-950 flex items-center gap-2">
          <Sparkles className="text-blue-600" size={20} />
          <span>4. AI Fixes Log</span>
        </h2>
        <p className="text-xs text-slate-500 mt-1">
          Review fixes generated by FixForge AI agents and track validation runs in Docker sandboxes.
        </p>
      </div>

      {/* Grid widgets */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="bg-white border border-slate-200 rounded-2xl p-4 shadow-sm flex items-center gap-4">
          <div className="w-10 h-10 rounded-xl bg-blue-50 flex items-center justify-center text-blue-600 font-bold text-lg">
            142
          </div>
          <div>
            <div className="text-slate-500 text-[10px] font-bold uppercase tracking-wider">Fixes Suggested</div>
            <div className="text-slate-900 font-bold text-sm">Automatic patches generated</div>
          </div>
        </div>

        <div className="bg-white border border-slate-200 rounded-2xl p-4 shadow-sm flex items-center gap-4">
          <div className="w-10 h-10 rounded-xl bg-emerald-50 flex items-center justify-center text-emerald-600 font-bold text-lg">
            96%
          </div>
          <div>
            <div className="text-slate-500 text-[10px] font-bold uppercase tracking-wider">Validation Success</div>
            <div className="text-slate-900 font-bold text-sm">Passed docker test suite</div>
          </div>
        </div>

        <div className="bg-white border border-slate-200 rounded-2xl p-4 shadow-sm flex items-center gap-4">
          <div className="w-10 h-10 rounded-xl bg-violet-50 flex items-center justify-center text-violet-600 font-bold text-lg">
            104
          </div>
          <div>
            <div className="text-slate-500 text-[10px] font-bold uppercase tracking-wider">Merged PRs</div>
            <div className="text-slate-900 font-bold text-sm">Successfully merged code</div>
          </div>
        </div>
      </div>

      {/* Recent fixes cards */}
      <div className="space-y-4">
        <h3 className="text-xs font-bold text-slate-400 uppercase tracking-widest">Recent patches</h3>
        
        <div className="grid grid-cols-1 gap-3">
          {fixes.map((fix) => (
            <div
              key={fix.id}
              className="bg-white border border-slate-200 rounded-2xl p-4 hover:shadow-sm transition-all flex flex-col md:flex-row md:items-center justify-between gap-4"
            >
              <div className="flex items-start gap-3.5">
                <div className="w-9 h-9 rounded-xl bg-slate-50 border border-slate-100 flex items-center justify-center text-slate-500 font-mono text-[10px] font-bold shrink-0">
                  {fix.id.split("-")[1]}
                </div>
                <div>
                  <h4 className="text-sm font-bold text-slate-950 flex items-center gap-2">
                    <span>{fix.title}</span>
                    <span className="text-[10px] font-mono font-bold text-slate-400 bg-slate-100 px-1 py-0.5 rounded">
                      Issue #{fix.issueId}
                    </span>
                  </h4>
                  <div className="flex flex-wrap items-center gap-3 mt-1 text-[11px] text-slate-500">
                    <span className="font-mono text-slate-700 flex items-center gap-1">
                      <Code2 size={12} className="text-slate-400" />
                      <span>{fix.file}</span>
                    </span>
                    <span>•</span>
                    <span className="flex items-center gap-1">
                      <Clock size={12} className="text-slate-300" />
                      <span>{fix.completedAt}</span>
                    </span>
                  </div>
                </div>
              </div>

              {/* Status parameters */}
              <div className="flex items-center gap-4 text-xs font-semibold shrink-0">
                <div className="text-right hidden sm:block">
                  <div className="text-slate-400 text-[10px] uppercase font-bold">Confidence</div>
                  <div className="text-slate-900 font-mono font-bold">{fix.confidence}%</div>
                </div>

                <div>
                  <div className="text-slate-400 text-[10px] uppercase font-bold mb-1">Docker Validation</div>
                  <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-lg text-[10px] font-bold uppercase border ${
                    fix.testStatus === "passed"
                      ? "bg-emerald-50 text-emerald-700 border-emerald-100"
                      : fix.testStatus === "running"
                      ? "bg-blue-50 text-blue-700 border-blue-100 animate-pulse"
                      : "bg-rose-50 text-rose-700 border-rose-100"
                  }`}>
                    {fix.testStatus}
                  </span>
                </div>

                <div>
                  <div className="text-slate-400 text-[10px] uppercase font-bold mb-1">Patch Status</div>
                  <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-lg text-[10px] font-bold uppercase border ${
                    fix.status === "applied"
                      ? "bg-blue-50 text-blue-700 border-blue-100"
                      : fix.status === "reviewing"
                      ? "bg-amber-50 text-amber-700 border-amber-100"
                      : "bg-slate-50 text-slate-500 border-slate-100"
                  }`}>
                    {fix.status}
                  </span>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
